image: gradle:latest

variables: 
  VERSION: "$CI_PROJECT_ID.$CI_COMMIT_BRANCH.$CI_COMMIT_SHORT_SHA"

stages:          
  - test
  - coverage


unit-test-job:  
  stage: test
  script:
    - gradle test
    

coverage:
  stage: coverage
  script:
    - gradle test
    - gradle jacocoTestReport
    - awk -F "," '{instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' `find . -name "jacocoTestReport.csv"`
  when: always
  coverage: '/([0-9]{1,3}.[0-9]*).%.covered/'


